### ISSUE TITLE
Bash Parameter expansion

### ISSUE THREAD

**Issue by babarot** [iBenza/bashtub#14]
提案です。

Case modification (`${PARAMETER^}`) は [bash 4 に依存した機能](http://tldp.org/LDP/abs/html/bashver4.html)です。
ソースコードを見たところ、4.0+ を要求しているのがここだけのようなので、違う書き方にすることによってより多くの bash 環境で使用できるようになるかと思います。

https://github.com/ueokande/bashtub/blob/master/bin/bashtub#L14

**Comment by ueokande** [comment]
@b4b4r07 ご指摘ありがとうございます。bash4未満のバージョンのテスト環境を作ってから、対応したいと思います。
